### ISSUE TITLE
Extra points

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2018-19-4ahif/vehicle-model-browser-exercise-danipalli#1]
Dear Mr. Stropek,

i finished off the required exercises to gain the two exra points.
You can take a look at my solution under the following url: https://dreamy-bartik-037639.netlify.com

Kind Regards
Daniel Pallinger

**Comment by rstropek** [comment]
Well done 👍. Your layout looks really nice. Of course the extra points are yours.

Greetings,
Rainer Stropek.
